### ISSUE TITLE
Can't apply flex grow

### ISSUE THREAD

**Issue by emahadzimustafic** [emahadzimustafic/web-design-2-independent-project#10]
Hi @thatkidmadrid, I'm having trouble applying flex-grow to my cards. I applied a grid to my ul. I tried using the <div class="apply-flex"> in my code but it hasn't worked so far. I'm sure I'm doing it wrong but I can't figure it out. 
![css-code](https://user-images.githubusercontent.com/77508090/145731976-59247ac0-2491-4473-9f8f-d343d14bf5c3.JPG)

**Comment by thatkidmadrid** [comment]
Please make sure you push your changes so that I'm able to see what you're seeing! I don't see this div with the class `appy-flex` nor do I see that class in your css

**Comment by emahadzimustafic** [comment]
Just pushed it - sorry about that

**Comment by thatkidmadrid** [comment]
ok I still don't see a class with `appy-flex` or `apply-flex` could you describe what you're trying to do with flex-grow?

**Comment by emahadzimustafic** [comment]
I want to make these cards even by using flex grow. I cant get it to work
![uneven cards](https://user-images.githubusercontent.com/77508090/145732616-025aa5f2-2b00-40ec-b8e6-5c4e4642fd5b.JPG)
![design-css](https://user-images.githubusercontent.com/77508090/145732628-963e81ff-6515-408c-a68c-5d2c7bc0330c.JPG)
![css-code](https://user-images.githubusercontent.com/77508090/145732629-997a5324-f059-4d80-8159-f34033cb10cd.JPG)

I fixed it to **apply flex**

**Comment by thatkidmadrid** [comment]
ok I see! are all of your images going to be the same size?

## If the images are the same size::

You can give `.cards li` `height: 100%` to fill the css grid cell.

Then you can give an elenment inside those flexible `<li>`s `flex-grow: 1`. I think giving this to the `<p>` tags makes sense, but that's up to you.

## If the images aren't the same size:

You can play around with the flex-grow values for all the elements inside the `<li>`s
![Screen Shot 2021-12-12 at 5 54 58 PM](https://user-images.githubusercontent.com/6340290/145732909-8ceee81c-9028-4bb2-b412-e520768e3a40.png)

(in my tests I gave the `<img>`s an explicit height to make the flexible `<p>`s obvious, otherwise the empty images flex by default

**Comment by emahadzimustafic** [comment]
Thank you, that worked.

Edit: Below issue was FIXED! but now **my nav and logo button doesn't work. Please help.** When I turn off width:100% for .banner-text in index.html, the nav works. For some reason, everything works on the-solution.html (with witdh:100%), but it doesn't work on the other two pages. It works if I change the nav order in my HTML, which isn't ideal.
![nav-header-logo doesnt work before banner text](https://user-images.githubusercontent.com/77508090/145741495-b35df2e9-dd04-4642-acdb-3f2f4e7b4c42.JPG)


--

I noticed that my banner text (eg. The Design: How social media apps are designed to keep you addicted; uses .banner-text class) on all of my pages doesn't stay in the center when I extend the page vertically. Is there an easy fix for this?
![banner-text](https://user-images.githubusercontent.com/77508090/145734280-f502ba22-46f9-4810-a3a6-d9a1dac35e3d.JPG)

**Comment by thatkidmadrid** [comment]
The key here is to give the header a `height: 100%` and `position: relative` so that the `.banner-text` which has `position: absolute` is positioned relative to the header.
![Screen Shot 2021-12-12 at 9 23 32 PM](https://user-images.githubusercontent.com/6340290/145742769-451f1c89-57e6-4372-823b-f500587ec890.png)

**Comment by thatkidmadrid** [comment]
also, I noticed your skip links are hidden behind your logo, you can just give it a decent z-index like `z-index: 10` and this would be a lot more useable! (You will also need to remove the `grid-area: banner` from the skip links when you do this to keep the functionality of your nav; it doesn't need to be part of the grid system because it will be hidden by default)
